### ISSUE TITLE
`foo.bar` added if url starts with `/`

### ISSUE THREAD

**Issue by lukaszmn** [posthtml/posthtml-cache#20]
Please explain what is the purpose of prepending the URL with `foo.bar` if it starts with `/`.

I have a 
```
<script src="/script.js"></script>
```

and it gets changed to:

```
<script src="foo.bar/script.js?v=3DW9E4NGiPsIFRZipbZYR"></script>
```

It breaks the link. I guess that `foo.bar` is added to let `normalizeUrl()` work, but later it's only disturbing. What about changing line 14 from

```
let [uri, query] = fullUrl.split('?');
```

to

```
let [uri, query] = url.split('?');
```

**Comment by Scrum** [comment]
@lukaszmn Hi, sorry for the long reply.

On the move there is no suggestion why this was done so. I have nothing against your proposal, feel free to relate

**Comment by lukaszmn** [comment]
I'm fixing it, but I'm curious how is this possible:

I cannot commit because the *existing* files do not pass husky/lint validation. So how did they appear in the branch?
